# Generated by Django 6.0.2 on 2026-03-06 08:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('CNO', 'Chief Nursing Officer'), ('SYSADMIN', 'System Admin')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clinic')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClinicKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_patients', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('emergency_cases', models.IntegerField()),
                ('critical_cases', models.IntegerField()),
                ('icu_transfers', models.IntegerField()),
                ('mortality_count', models.IntegerField()),
                ('staff_on_duty', models.IntegerField()),
                ('nurses_absent', models.IntegerField()),
                ('overtime_hours', models.IntegerField()),
                ('unattended_critical_cases', models.IntegerField()),
                ('power_outage_hours', models.IntegerField()),
                ('internet_downtime_hours', models.IntegerField()),
                ('stockout_oxygen', models.BooleanField()),
                ('stockout_essential_drugs', models.BooleanField()),
                ('bed_occupancy_rate', models.FloatField()),
                ('readmission_rate', models.FloatField()),
                ('patient_complaints', models.IntegerField()),
                ('malaria_cases', models.IntegerField(default=0)),
                ('cholera_cases', models.IntegerField(default=0)),
                ('respiratory_cases', models.IntegerField(default=0)),
                ('triage_wait_time', models.IntegerField(default=0)),
                ('lab_turnaround_time', models.IntegerField(default=0)),
                ('pharmacy_wait_time', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('training_coverage', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
            ],
        ),
    ]
