# Generated by Django 6.0.2 on 2026-03-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinickpi',
            name='shift_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clinickpi',
            unique_together={('clinic', 'shift', 'shift_date')},
        ),
    ]
