# Generated by Django 6.0.2 on 2026-03-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clinickpi_shift_date_alter_clinickpi_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='timezone',
            field=models.CharField(default='UTC', max_length=60),
        ),
    ]
