# Generated by Django 6.0.2 on 2026-03-09 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinickpi')),
            ],
        ),
    ]
