# Generated by Django 6.0.2 on 2026-03-10 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_clinicrisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinickpi')),
            ],
        ),
        migrations.DeleteModel(
            name='ClinicRisk',
        ),
    ]
