# Generated by Django 6.0.2 on 2026-03-10 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_riskprediction_delete_clinicrisk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprediction',
            name='kpi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.clinickpi'),
        ),
    ]
